### ISSUE TITLE
[MC 1.19.4]Crashed when the world finished loading

### ISSUE THREAD

**Issue by Silicon7921** [mineblock11/snow-under-trees-fabric#1]
the mod causes Minecraft to crash when the world finishes loading

it seems to be a render thread error
[2023-05-01-7.log](https://github.com/mineblock11/snow-under-trees-fabric/files/11364950/2023-05-01-7.log)

here is the logfile.hope this can help you

your project is really great, but it will be greater without this problem.hope the bug can be fixed soon!

**Comment by mineblock11** [comment]
Hi, this crash isn't related to snow under trees. It seems to be related to a modded item, which this mod does not add.
Please check if any other mods are crashing, as it may not be this one.

Closing for now.
