### ISSUE TITLE
Mod not works on modded biomes

### ISSUE THREAD

**Issue by IntM4rco** [mineblock11/snow-under-trees-fabric#2]
### Custom biomes are not already generated with snow under the trees. (If you notice any blocks with snow, it's because I had accidentally made it snow).
![2023-08-08_15 34 18](https://github.com/mineblock11/snow-under-trees-fabric/assets/124934175/76ec5dc7-b932-4004-99a2-73c70edaf3dc)

**Comment by mineblock11** [comment]
You'll have to add the modded biome's ID in the supported biomes list in the config. You can find the biome ID in the F3 screen.
